name: Find File Changes

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch both commits

      - name: Set commit SHAs
        run: |
          PREV_SHA=$(git rev-parse HEAD~2)
          CURR_SHA=$(git rev-parse HEAD)
          echo "Previous commit SHA: $PREV_SHA"
          echo "Current commit SHA: $CURR_SHA"

      - name: Get file changes
        run: |
          CHANGES=$(git diff --name-only $PREV_SHA $CURR_SHA -- "./file1")
          echo "Changes in file1: $CHANGES"

      - name: Output changed files
        id: get_file_changes
        run: echo "file-changed=1" >> $GITHUB_ENV

      - name: Display changes
        if: steps.get_file_changes.outputs['file-changed'] == '1'
        run: |
          echo "File changed: ${{ steps.get_file_changes.outputs.file-changed }}"
          echo "Changes made in file1:"
          git diff $PREV_SHA $CURR_SHA -- "./file1"
