name: Find File Changes

on: workflow_dispatch

jobs:
  find-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set commit SHAs
        run: |
          PREV_SHA=$(git log -n 2 --format="%H" | tail -n 2 | head -n 1)
          CURR_SHA=$(git rev-parse HEAD)
          echo "Previous commit SHA: $PREV_SHA"
          echo "Current commit SHA: $CURR_SHA"

      - name: Get file changes
        run: |
          CHANGES=$(git diff $PREV_SHA $CURR_SHA -- "file1")
          echo "Changes in file1:"
          echo "$CHANGES"

      - name: Display changes
        run: echo "Changes in file1:$CHANGES"

      - name: show content
        run: git show $CURR_SHA:file1
