name: S3 Data Cleanup

on: workflow_dispatch
  

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your desired region

  delete-old-data:
    runs-on: ubuntu-latest

    steps:
    - name: Set up AWS CLI
      run: aws configure set region us-east-2

    - name: Delete old data in S3
      run: |
        aws s3 rm s3://testingbucket1252 --recursive --exclude "*" --include "$(date -d '15 days ago' '+%Y-%m-%d')/*"
